sf-backwoods/objects/Adventurer__c/Adventurer__c.object-meta.xml
<CustomObject>
    <label>Adventurer</label>
    <nameField>
        <label>Adventurer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Adventurers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sf-backwoods/objects/Adventurer__c/fields/Experience_Points__c.field-meta.xml
<CustomField>
    <fullName>Experience_Points__c</fullName>
    <label>Experience Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sf-backwoods/objects/Adventurer__c/fields/Story_Points__c.field-meta.xml
<CustomField>
    <fullName>Story_Points__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Stories are bite sized challenges/tasks/etc that are assigned points prior to staring. Points can be adjusted after the fact, which can help in the estimation process. Their points are earned when stories are done-done.</description>
    <label>Story Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/habitica/UtilityService.cls
public with sharing class UtilityService {

    public static Adventurer__c getCurrentAdventurer() {
        List<Adventurer__c> adventurers = [SELECT Id, Experience_Points__c, Story_Points__c FROM Adventurer__c WHERE OwnerId = :UserInfo.getUserId() LIMIT 1];
        Adventurer__c adventurer = (adventurers.size() == 1) ? adventurers.get(0) : null;
        if (adventurer == null) {
            Logger.warn('Adventurer not found for ' + UserInfo.getName());
            Logger.saveLog();
        }
        return adventurer;
    }

    public static Adventurer__c getMyAdventurer() {
        List<Adventurer__c> adventurers = [SELECT Id, Experience_Points__c FROM Adventurer__c WHERE Name = 'Panda Power' LIMIT 1];
        Adventurer__c adventurer = (adventurers.size() == 1) ? adventurers.get(0) : null;
        if (adventurer == null) {
            Logger.warn('Adventurer not found for ' + UserInfo.getName());
            Logger.saveLog();
        }
        return adventurer;
    }
}